{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMHeNJZIRj2N7GxtjzguS5A",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/sagasucksatlife1/COMMISION_REPO/blob/main/Database.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "id": "zuV_nC7gxL8d"
      },
      "outputs": [],
      "source": [
        "import sqlite3\n",
        "from datetime import datetime\n",
        "import hashlib\n",
        "import secrets\n",
        "\n",
        "class Database:\n",
        "    def __init__(self, db_name=\"/data/commission_system.db\"):\n",
        "        self.db_name = db_name\n",
        "        self.init_db()\n",
        "\n",
        "    def get_connection(self):\n",
        "        conn = sqlite3.connect(self.db_name)\n",
        "        conn.row_factory = sqlite3.Row\n",
        "        return conn\n",
        "\n",
        "    def init_db(self):\n",
        "        conn = self.get_connection()\n",
        "        cursor = conn.cursor()\n",
        "        cursor.execute('''CREATE TABLE IF NOT EXISTS users (\n",
        "            id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
        "            username TEXT UNIQUE NOT NULL,\n",
        "            password_hash TEXT NOT NULL,\n",
        "            role TEXT NOT NULL CHECK(role IN ('employee', 'admin')),\n",
        "            full_name TEXT NOT NULL,\n",
        "            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n",
        "        )''')\n",
        "        cursor.execute('''CREATE TABLE IF NOT EXISTS commissions (\n",
        "            id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
        "            user_id INTEGER NOT NULL,\n",
        "            sale_date DATE NOT NULL,\n",
        "            unlisted_sales REAL NOT NULL DEFAULT 0,\n",
        "            loans REAL NOT NULL DEFAULT 0,\n",
        "            third_party_sales REAL NOT NULL DEFAULT 0,\n",
        "            calculated_commission REAL NOT NULL,\n",
        "            status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'approved', 'rejected')),\n",
        "            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n",
        "            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n",
        "            FOREIGN KEY (user_id) REFERENCES users(id)\n",
        "        )''')\n",
        "        cursor.execute('''CREATE TABLE IF NOT EXISTS sessions (\n",
        "            id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
        "            user_id INTEGER NOT NULL,\n",
        "            token TEXT UNIQUE NOT NULL,\n",
        "            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n",
        "            expires_at TIMESTAMP NOT NULL,\n",
        "            FOREIGN KEY (user_id) REFERENCES users(id)\n",
        "        )''')\n",
        "        conn.commit()\n",
        "        conn.close()\n",
        "        self.create_default_admin()\n",
        "\n",
        "    def hash_password(self, password):\n",
        "        return hashlib.sha256(password.encode()).hexdigest()\n",
        "\n",
        "    def create_default_admin(self):\n",
        "        conn = self.get_connection()\n",
        "        cursor = conn.cursor()\n",
        "        cursor.execute(\"SELECT * FROM users WHERE username = ?\", (\"admin\",))\n",
        "        if not cursor.fetchone():\n",
        "            password_hash = self.hash_password(\"admin123\")\n",
        "            cursor.execute('INSERT INTO users (username, password_hash, role, full_name) VALUES (?, ?, ?, ?)',\n",
        "                         (\"admin\", password_hash, \"admin\", \"System Admin\"))\n",
        "            conn.commit()\n",
        "        conn.close()\n",
        "\n",
        "    def create_user(self, username, password, role, full_name):\n",
        "        conn = self.get_connection()\n",
        "        cursor = conn.cursor()\n",
        "        try:\n",
        "            cursor.execute('INSERT INTO users (username, password_hash, role, full_name) VALUES (?, ?, ?, ?)',\n",
        "                         (username, self.hash_password(password), role, full_name))\n",
        "            conn.commit()\n",
        "            user_id = cursor.lastrowid\n",
        "            conn.close()\n",
        "            return user_id\n",
        "        except sqlite3.IntegrityError:\n",
        "            conn.close()\n",
        "            return None\n",
        "\n",
        "    def verify_user(self, username, password):\n",
        "        conn = self.get_connection()\n",
        "        cursor = conn.cursor()\n",
        "        cursor.execute('SELECT id, username, role, full_name FROM users WHERE username = ? AND password_hash = ?',\n",
        "                      (username, self.hash_password(password)))\n",
        "        user = cursor.fetchone()\n",
        "        conn.close()\n",
        "        return dict(user) if user else None\n",
        "\n",
        "    def create_session(self, user_id):\n",
        "        conn = self.get_connection()\n",
        "        cursor = conn.cursor()\n",
        "        token = secrets.token_urlsafe(32)\n",
        "        expires_at = datetime.now().timestamp() + (24 * 60 * 60)\n",
        "        cursor.execute('INSERT INTO sessions (user_id, token, expires_at) VALUES (?, ?, datetime(?, \"unixepoch\"))',\n",
        "                      (user_id, token, expires_at))\n",
        "        conn.commit()\n",
        "        conn.close()\n",
        "        return token\n",
        "\n",
        "    def verify_session(self, token):\n",
        "        conn = self.get_connection()\n",
        "        cursor = conn.cursor()\n",
        "        cursor.execute('''SELECT s.user_id, u.username, u.role, u.full_name FROM sessions s\n",
        "                         JOIN users u ON s.user_id = u.id WHERE s.token = ? AND s.expires_at > datetime('now')''', (token,))\n",
        "        session = cursor.fetchone()\n",
        "        conn.close()\n",
        "        return dict(session) if session else None\n",
        "\n",
        "    def delete_session(self, token):\n",
        "        conn = self.get_connection()\n",
        "        cursor = conn.cursor()\n",
        "        cursor.execute(\"DELETE FROM sessions WHERE token = ?\", (token,))\n",
        "        conn.commit()\n",
        "        conn.close()\n",
        "\n",
        "    def create_commission(self, user_id, sale_date, unlisted_sales, loans, third_party_sales):\n",
        "        calculated_commission = (loans / 3) + (unlisted_sales / 3) + (third_party_sales * 100)\n",
        "        conn = self.get_connection()\n",
        "        cursor = conn.cursor()\n",
        "        cursor.execute('INSERT INTO commissions (user_id, sale_date, unlisted_sales, loans, third_party_sales, calculated_commission) VALUES (?, ?, ?, ?, ?, ?)',\n",
        "                      (user_id, sale_date, unlisted_sales, loans, third_party_sales, calculated_commission))\n",
        "        conn.commit()\n",
        "        commission_id = cursor.lastrowid\n",
        "        conn.close()\n",
        "        return commission_id\n",
        "\n",
        "    def update_commission(self, commission_id, user_id, sale_date, unlisted_sales, loans, third_party_sales):\n",
        "        calculated_commission = (loans / 3) + (unlisted_sales / 3) + (third_party_sales * 100)\n",
        "        conn = self.get_connection()\n",
        "        cursor = conn.cursor()\n",
        "        cursor.execute('UPDATE commissions SET sale_date=?, unlisted_sales=?, loans=?, third_party_sales=?, calculated_commission=?, updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?',\n",
        "                      (sale_date, unlisted_sales, loans, third_party_sales, calculated_commission, commission_id, user_id))\n",
        "        conn.commit()\n",
        "        affected = cursor.rowcount\n",
        "        conn.close()\n",
        "        return affected > 0\n",
        "\n",
        "    def delete_commission(self, commission_id, user_id):\n",
        "        conn = self.get_connection()\n",
        "        cursor = conn.cursor()\n",
        "        cursor.execute('DELETE FROM commissions WHERE id=? AND user_id=?', (commission_id, user_id))\n",
        "        conn.commit()\n",
        "        affected = cursor.rowcount\n",
        "        conn.close()\n",
        "        return affected > 0\n",
        "\n",
        "    def get_user_commissions(self, user_id, months=1):\n",
        "        conn = self.get_connection()\n",
        "        cursor = conn.cursor()\n",
        "        cursor.execute('SELECT * FROM commissions WHERE user_id=? AND sale_date >= date(\"now\", \"-\" || ? || \" months\") ORDER BY sale_date DESC',\n",
        "                      (user_id, months))\n",
        "        commissions = [dict(row) for row in cursor.fetchall()]\n",
        "        conn.close()\n",
        "        return commissions\n",
        "\n",
        "    def get_all_commissions(self, months=1, employee_id=None):\n",
        "        conn = self.get_connection()\n",
        "        cursor = conn.cursor()\n",
        "        if employee_id:\n",
        "            cursor.execute('SELECT c.*, u.full_name as employee_name FROM commissions c JOIN users u ON c.user_id=u.id WHERE c.user_id=? AND c.sale_date >= date(\"now\", \"-\" || ? || \" months\") ORDER BY c.sale_date DESC',\n",
        "                          (employee_id, months))\n",
        "        else:\n",
        "            cursor.execute('SELECT c.*, u.full_name as employee_name FROM commissions c JOIN users u ON c.user_id=u.id WHERE c.sale_date >= date(\"now\", \"-\" || ? || \" months\") ORDER BY c.sale_date DESC',\n",
        "                          (months,))\n",
        "        commissions = [dict(row) for row in cursor.fetchall()]\n",
        "        conn.close()\n",
        "        return commissions\n",
        "\n",
        "    def update_commission_status(self, commission_id, status):\n",
        "        conn = self.get_connection()\n",
        "        cursor = conn.cursor()\n",
        "        cursor.execute('UPDATE commissions SET status=?, updated_at=CURRENT_TIMESTAMP WHERE id=?', (status, commission_id))\n",
        "        conn.commit()\n",
        "        affected = cursor.rowcount\n",
        "        conn.close()\n",
        "        return affected > 0\n",
        "\n",
        "    def get_all_employees(self):\n",
        "        conn = self.get_connection()\n",
        "        cursor = conn.cursor()\n",
        "        cursor.execute('SELECT id, username, full_name FROM users WHERE role=\"employee\" ORDER BY full_name')\n",
        "        employees = [dict(row) for row in cursor.fetchall()]\n",
        "        conn.close()\n",
        "        return employees\n",
        "\n"
      ]
    }
  ]
}