{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/sagasucksatlife1/COMMISION_REPO/blob/main/main.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from fastapi import FastAPI, HTTPException, Depends, Header\n",
        "from fastapi.middleware.cors import CORSMiddleware\n",
        "from fastapi.responses import StreamingResponse\n",
        "from pydantic import BaseModel\n",
        "from typing import Optional\n",
        "from datetime import datetime\n",
        "import io\n",
        "import csv\n",
        "from database import Database\n",
        "\n",
        "app = FastAPI()\n",
        "app.add_middleware(CORSMiddleware, allow_origins=[\"*\"], allow_credentials=True, allow_methods=[\"*\"], allow_headers=[\"*\"])\n",
        "db = Database()\n",
        "\n",
        "class LoginRequest(BaseModel):\n",
        "    username: str\n",
        "    password: str\n",
        "\n",
        "class CreateUserRequest(BaseModel):\n",
        "    username: str\n",
        "    password: str\n",
        "    role: str\n",
        "    full_name: str\n",
        "\n",
        "class CommissionRequest(BaseModel):\n",
        "    sale_date: str\n",
        "    unlisted_sales: float\n",
        "    loans: float\n",
        "    third_party_sales: float\n",
        "\n",
        "class UpdateCommissionRequest(BaseModel):\n",
        "    commission_id: int\n",
        "    sale_date: str\n",
        "    unlisted_sales: float\n",
        "    loans: float\n",
        "    third_party_sales: float\n",
        "\n",
        "class UpdateStatusRequest(BaseModel):\n",
        "    commission_id: int\n",
        "    status: str\n",
        "\n",
        "def get_current_user(authorization: Optional[str] = Header(None)):\n",
        "    if not authorization:\n",
        "        raise HTTPException(status_code=401, detail=\"Not authenticated\")\n",
        "    user = db.verify_session(authorization.replace(\"Bearer \", \"\"))\n",
        "    if not user:\n",
        "        raise HTTPException(status_code=401, detail=\"Invalid token\")\n",
        "    return user\n",
        "\n",
        "def require_admin(current_user: dict = Depends(get_current_user)):\n",
        "    if current_user[\"role\"] != \"admin\":\n",
        "        raise HTTPException(status_code=403, detail=\"Admin access required\")\n",
        "    return current_user\n",
        "\n",
        "@app.post(\"/api/auth/login\")\n",
        "def login(request: LoginRequest):\n",
        "    user = db.verify_user(request.username, request.password)\n",
        "    if not user:\n",
        "        raise HTTPException(status_code=401, detail=\"Invalid credentials\")\n",
        "    token = db.create_session(user[\"id\"])\n",
        "    return {\"token\": token, \"user\": user}\n",
        "\n",
        "@app.post(\"/api/auth/logout\")\n",
        "def logout(authorization: Optional[str] = Header(None)):\n",
        "    if authorization:\n",
        "        db.delete_session(authorization.replace(\"Bearer \", \"\"))\n",
        "    return {\"message\": \"Logged out\"}\n",
        "\n",
        "@app.get(\"/api/auth/me\")\n",
        "def get_me(current_user: dict = Depends(get_current_user)):\n",
        "    return current_user\n",
        "\n",
        "@app.post(\"/api/users/create\")\n",
        "def create_user(request: CreateUserRequest, _: dict = Depends(require_admin)):\n",
        "    user_id = db.create_user(request.username, request.password, request.role, request.full_name)\n",
        "    if not user_id:\n",
        "        raise HTTPException(status_code=400, detail=\"Username exists\")\n",
        "    return {\"message\": \"User created\", \"user_id\": user_id}\n",
        "\n",
        "@app.get(\"/api/users/employees\")\n",
        "def get_employees(_: dict = Depends(require_admin)):\n",
        "    return {\"employees\": db.get_all_employees()}\n",
        "\n",
        "@app.post(\"/api/commissions/create\")\n",
        "def create_commission(request: CommissionRequest, current_user: dict = Depends(get_current_user)):\n",
        "    commission_id = db.create_commission(current_user[\"user_id\"], request.sale_date, request.unlisted_sales, request.loans, request.third_party_sales)\n",
        "    return {\"message\": \"Created\", \"commission_id\": commission_id}\n",
        "\n",
        "@app.put(\"/api/commissions/update\")\n",
        "def update_commission(request: UpdateCommissionRequest, current_user: dict = Depends(get_current_user)):\n",
        "    if not db.update_commission(request.commission_id, current_user[\"user_id\"], request.sale_date, request.unlisted_sales, request.loans, request.third_party_sales):\n",
        "        raise HTTPException(status_code=404, detail=\"Not found\")\n",
        "    return {\"message\": \"Updated\"}\n",
        "\n",
        "@app.delete(\"/api/commissions/{commission_id}\")\n",
        "def delete_commission(commission_id: int, current_user: dict = Depends(get_current_user)):\n",
        "    if not db.delete_commission(commission_id, current_user[\"user_id\"]):\n",
        "        raise HTTPException(status_code=404, detail=\"Not found\")\n",
        "    return {\"message\": \"Deleted\"}\n",
        "\n",
        "@app.get(\"/api/commissions/my\")\n",
        "def get_my_commissions(months: int = 1, current_user: dict = Depends(get_current_user)):\n",
        "    return {\"commissions\": db.get_user_commissions(current_user[\"user_id\"], months)}\n",
        "\n",
        "@app.get(\"/api/commissions/all\")\n",
        "def get_all_commissions(months: int = 1, employee_id: Optional[int] = None, _: dict = Depends(require_admin)):\n",
        "    return {\"commissions\": db.get_all_commissions(months, employee_id)}\n",
        "\n",
        "@app.put(\"/api/commissions/status\")\n",
        "def update_status(request: UpdateStatusRequest, _: dict = Depends(require_admin)):\n",
        "    if not db.update_commission_status(request.commission_id, request.status):\n",
        "        raise HTTPException(status_code=404, detail=\"Not found\")\n",
        "    return {\"message\": \"Updated\"}\n",
        "\n",
        "@app.get(\"/api/commissions/export\")\n",
        "def export_commissions(months: int = 1, employee_id: Optional[int] = None, _: dict = Depends(require_admin)):\n",
        "    commissions = db.get_all_commissions(months, employee_id)\n",
        "    output = io.StringIO()\n",
        "    writer = csv.writer(output)\n",
        "    writer.writerow([\"Employee\", \"Date\", \"Unlisted\", \"Loans\", \"Third-Party\", \"Commission\", \"Status\"])\n",
        "    for c in commissions:\n",
        "        writer.writerow([c[\"employee_name\"], c[\"sale_date\"], c[\"unlisted_sales\"], c[\"loans\"], c[\"third_party_sales\"], c[\"calculated_commission\"], c[\"status\"]])\n",
        "    output.seek(0)\n",
        "    return StreamingResponse(io.BytesIO(output.getvalue().encode()), media_type=\"text/csv\", headers={\"Content-Disposition\": f\"attachment; filename=commissions_{datetime.now().strftime('%Y%m%d')}.csv\"})\n",
        "\n",
        "@app.get(\"/\")\n",
        "def root():\n",
        "    return {\"message\": \"Commission System API\", \"status\": \"running\"}"
      ],
      "metadata": {
        "id": "R7I1po1lxqfg"
      },
      "execution_count": 2,
      "outputs": []
    }
  ],
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOt1Ivk0v/MzTEXcR8fHbh4",
      "include_colab_link": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}